services:
  - type: web
    name: ansa-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:10000 main:app"
    envVars:
      - key: FLASK_ENV
        value: production

  - type: web
    name: ansa-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://ansa-backend.onrender.com